server:
  port: 9001
  tomcat:
    connection-timeout: 2s # time between opening connection and receiving a http request
    keep-alive-timeout: 15s # time in which connection can accept multiple http requests
    threads:
      max: 50
      min-spare: 5

polar:
  greeting: Welcome to the local book catalog!
  testdata:
    enabled: false

spring:
  application:
    name: catalog-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false
      #retry runs only if fail-fast is true
      retry:
        max-attempts: 4
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
management:
  endpoints:
    web:
      exposure:
        include: refresh

